# Default: list available recipes.
default:
    @just --list

# Bootstrap a fresh checkout: sync deps, copy .env if missing, bring up compose, run migrations.
setup:
    uv sync
    [ -f .env ] || cp .env.example .env
    docker compose up -d --wait
    uv run alembic upgrade head
    just smoke-langfuse
    @echo ""
    @echo "Langfuse UI: http://localhost:3002"
    @echo "Login:       dev@rag-recipes.local / devdevdev (seeded in .env)"

# Submit a trace via the Langfuse SDK and verify it lands in the UI (web → Redis → worker → ClickHouse).
smoke-langfuse:
    uv run python scripts/smoke_langfuse.py

# Run API + worker in parallel under one process group; Ctrl-C tears down both.
# For per-process log streams during debugging, prefer two terminals:
# `just dev-api` in one and `just dev-worker` in the other.
dev:
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'kill 0' EXIT
    just dev-api &
    just dev-worker &
    wait

# Run the FastAPI app under uvicorn with autoreload.
# Host port 8004 (not 8000/8001) to avoid clashing with other local dev servers.
# NOT 8001: the cloudflared tunnel maps webhook.ivot.dev to :8001 for adw, so
# anything listening there is published to the internet without Access.
dev-api:
    uv run uvicorn rag_recipes.api.app:app --reload --port 8004

# Run the arq worker against compose Redis. Reads .env via uv run.
# `--watch src/` autoreloads on source changes (mirrors uvicorn --reload).
dev-worker:
    uv run arq rag_recipes.ingestion.jobs.WorkerSettings --watch src/

# Run the full test suite.
test:
    uv run pytest

# Run only the unit tests.
test-unit:
    uv run pytest tests/unit

# Run only the integration tests.
test-integration:
    uv run pytest tests/integration

# Run opt-in live tests that call real external APIs (needs OPENAI_API_KEY).
test-live:
    uv run pytest tests/live -m live

# Run ruff and mypy. Both must pass for the recipe to exit 0.
lint:
    uv run ruff check src/ tests/
    uv run mypy src/

# Format the codebase in place with ruff.
format:
    uv run ruff format src/ tests/

# Apply all pending Alembic migrations.
migrate:
    uv run alembic upgrade head

# Generate a new autogenerated Alembic revision: `just migration "describe change"`.
migration MSG:
    uv run alembic revision --autogenerate -m "{{MSG}}"

# Regenerate the self-contained HTML viewer for the epics + plans (stdlib only, no deps).
# Output: docs/implementation/epics-viewer.html — open it directly in a browser.
epics-viewer:
    python3 scripts/build_epics_viewer.py

# Stop the compose stack. Volumes are preserved.
down:
    docker compose down

# Stop the compose stack AND remove data volumes. Prompts before destroying data.
[confirm("Remove all data volumes? This deletes Postgres data. [y/N]")]
clean:
    docker compose down -v
