# Default: list available recipes.
default:
    @just --list

# Bootstrap a fresh checkout: sync deps, copy .env if missing, bring up compose, run migrations.
setup:
    uv sync
    [ -f .env ] || cp .env.example .env
    docker compose up -d --wait
    uv run alembic upgrade head
    just smoke-langfuse
    @echo ""
    @echo "Langfuse UI: http://localhost:3001"
    @echo "Login:       dev@rag-recipes.local / devdevdev (seeded in .env)"

# Submit a trace via the Langfuse SDK and verify it lands in the UI (web → Redis → worker → ClickHouse).
smoke-langfuse:
    uv run python scripts/smoke_langfuse.py

# Run the API with autoreload (alias for `just dev-api`).
dev: dev-api

# Run the FastAPI app under uvicorn with autoreload.
dev-api:
    uv run uvicorn rag_recipes.api.app:app --reload

# Placeholder until Epic 7 wires up the real arq worker.
dev-worker:
    @echo "arq worker not implemented until Epic 7 — recipe reserved."

# Run the full test suite.
test:
    uv run pytest

# Run only the unit tests.
test-unit:
    uv run pytest tests/unit

# Run only the integration tests.
test-integration:
    uv run pytest tests/integration

# Run opt-in live tests that call real external APIs (needs OPENAI_API_KEY).
test-live:
    uv run pytest tests/live -m live

# Run ruff and mypy. Both must pass for the recipe to exit 0.
lint:
    uv run ruff check src/ tests/
    uv run mypy src/

# Format the codebase in place with ruff.
format:
    uv run ruff format src/ tests/

# Apply all pending Alembic migrations.
migrate:
    uv run alembic upgrade head

# Generate a new autogenerated Alembic revision: `just migration "describe change"`.
migration MSG:
    uv run alembic revision --autogenerate -m "{{MSG}}"

# Stop the compose stack. Volumes are preserved.
down:
    docker compose down

# Stop the compose stack AND remove data volumes. Prompts before destroying data.
[confirm("Remove all data volumes? This deletes Postgres data. [y/N]")]
clean:
    docker compose down -v
